### ISSUE TITLE
Feature request:  backup rotation

### ISSUE THREAD

**Issue by sslupsky** [AAFC-MBB/matiri#16]
I could not see if your script supports backup rotation?  That is, can you expire a backup after a certain amount of time and automatically delete the expired backup?

**Comment by IyadKandalaft** [comment]
no, that was a planned feature but never implemented.

**Comment by sslupsky** [comment]
Apologies, I noticed this is the same as issue #1 

BTW, from what I have seen so far, these are very well written scripts.  Kudos.
